FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    FILESWIFT_DATA_DIR=/data

RUN echo "Instalando requisitos de produção..."
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

RUN echo "Instalando requisitos de desenvolvimento..."
COPY requirements.dev.txt /tmp/requirements.dev.txt
RUN pip install --no-cache-dir -r /tmp/requirements.dev.txt && \
    rm /tmp/requirements.dev.txt

RUN echo "Criando FileSwift data path e workspace..."
RUN mkdir -p /data
WORKDIR /workspace
